country = {
    "ascension island": "ac",
    "andorra": "ad",
    "the principality of andorra": "ad",
    "and": "ad",
    "united arab emirates": "ae",
    "the united arab emirates": "ae", 
    "are": "ae",
    "afghanistan": "af",
    "the islamic republic of afghanistan": "af",
    "afg": "af",
    "antigua and barbuda": "ag",
    "atg": "ag",
    "anguilla": "ai",
    "aia": "ai",
    "albania": "al", 
    "the republic of albania": "al", 
    "alb": "al",
    "armenia": "am",
    "the republic of armenia": "am", 
    "arm": "am",
    "angola": "ao",
    "the republic of angola": "ao",
    "ago": "ao",
    "antarctica": "aq", 
    "all land and ice shelves south of the 60th parallel south": "aq",
    "ata": "aq",
    "argentina": "ar",
    "the argentine republic": "ar",
    "arg": "ar",
    "american samoa": "as", 
    "the territory of american samoa": "as",
    "asm": "as",
    "austria": "at", 
    "the republic of austria": "at",
    "aut": "at",
    "australia": "au", 
    "aus": "au", 
    "the commonwealth of australia": "au",
    "aruba": "aw", 
    "abw": "aw",
    "åland islands": "ax", 
    "åland": "ax", 
    "ala": "ax", 
    "aland islands": "ax", 
    "aland": "ax",
    "azerbaijan": "az", 
    "the republic of azerbaijan": "az", 
    "aze": "az",
    "bosnia and herzegovina": "ba", 
    "bih": "ba",
    "barbados": "bb", 
    "brb": "bb",
    "bangladesh": "bd", 
    "the people's republic of bangladesh": "bd", 
    "bgd": "bd",
    "belgium": "be",
    "the kingdom of belgium": "be", 
    "bel": "be",
    "burkina faso": "bf", 
    "bfa": "bf",
    "bulgaria": "bg", 
    "the republic of bulgaria": "bg",
    "bgr": "bg",
    "bahrain": "bh", 
    "the kingdom of bahrain": "bh", 
    "bhr": "bh",
    "burundi": "bi", 
    "the republic of burundi": "bi", 
    "bdi": "bi",
    "benin": "bj", 
    "the republic of benin": "bj", 
    "ben": "bj",
    "saint-barthélemy": "bl", 
    "saint-barthelemy": "bl", 
    "saint barthelemy": "bl",
    "the collectivity of saint-barthelemy": "bl",
    "saint barthélemy": "bl",
    "the collectivity of saint-barthélemy": "bl", 
    "blm": "bl",
    "bermuda": "bm", 
    "bmu": "bm",
    "brunei darussalam": "bn", 
    "brn": "bn", 
    "the nation of brunei, the abode of peace": "bn",
    "the plurinational state of bolivia": "bo", 
    "bol": "bo", 
    "bolivia": "bo",
    "saint eustatius": "bq", 
    "sint eustatius": "bq", 
    "saba": "bq", 
    "bonaire": "bq", 
    "bonaire, sint eustatius and saba": "bq", 
    "bes": "bq",
    "brazil": "br", 
    "the federative republic of brazil": "br", 
    "bra": "br",
    "bahamas": "bs", 
    "the commonwealth of the bahamas": "bs", 
    "bhs": "bs", 
    "the bahamas": "bs",
    "bhutan": "bt", 
    "the kingdom of bhutan": "bt", 
    "btn": "bt",
    "bouvet island": "bv", 
    "bvt": "bv",
    "botswana": "bw", 
    "the republic of botswana": "bw", 
    "bwa": "bw",
    "belarus": "by", 
    "the republic of belarus": "by", 
    "blr": "by",
    "belize": "bz", 
    "blz": "bz",
    "canada": "ca", 
    "can": "ca",
    "cocos islands": "cc", 
    "the cocos islands": "cc", 
    "the cocos (keeling) islands": "cc", 
    "the territory of cocos islands": "cc", 
    "cck": "cc",
    "democratic republic of the congo": "cd", 
    "the democratic republic of the congo": "cd", 
    "cod": "cd", 
    "congo": "cd",
    "african republic": "cf", 
    "central african republic": "cf", 
    "the central african republic": "cf", 
    "caf": "cf",
    "congo": "cg", 
    "the republic of the congo": "cg", 
    "cog": "cg", 
    "the congo": "cg",
    "switzerland": "ch", 
    "the swiss confederation": "ch", 
    "che": "ch",
    "cote d'ivoire": "ci", 
    "the republic of cote d'ivoire": "ci", 
    "côte d'ivoire": "ci", 
    "the republic of côte d'ivoire": "ci", 
    "civ": "ci",
    "cook islands": "ck", 
    "the cook islands": "ck", 
    "cok": "ck",
    "chile": "cl", 
    "the republic of chile": "cl", 
    "chl": "cl",
    "cameroon": "cm", 
    "the republic of cameroon": "cm", 
    "cmr": "cm",
    "china": "cn", 
    "the people's republic of china": "cn", 
    "chn": "cn",
    "colombia": "co", 
    "the republic of colombia": "co", 
    "col": "co",
    "cp": "clipperton island",
    "costa rica": "cr", 
    "the republic of costa rica": "cr", 
    "cri": "cr",
    "cuba": "cu", 
    "the republic of cuba": "cu", 
    "cub": "cu",
    "cabo verde": "cv", 
    "the republic of cabo verde": "cv", 
    "cpv": "cv",
    "curacao": "cw",
    "the country of curacao": "cw",
    "curaçao": "cw", 
    "the country of curaçao": "cw", 
    "cuw": "cw",
    "christmas island": "cx", 
    "the territory of christmas island": "cx", 
    "cxr": "cx",
    "cyprus": "cy", 
    "the republic of cyprus": "cy", 
    "cyp": "cy",
    "czechia": "cz", 
    "czech republic": "cz", 
    "the czech republic": "cz", 
    "cze": "cz",
    "germany": "de", 
    "the federal republic of germany": "de", 
    "deu": "de",
    "grenada": "dg", 
    "grd": "dg",
    "djibouti": "dj",
    "the republic of djibouti": "dj", 
    "dji": "dj",
    "denmark": "dk", 
    "the kingdom of denmark": "dk", 
    "dnk": "dk",
    "dominica": "dm", 
    "the commonwealth of dominica": "dm", 
    "dma": "dm",
    "dominican republic": "do", 
    "the dominican republic": "do", 
    "dom": "do",
    "algeria": "dz", 
    "the people's democratic republic of algeria": "dz", 
    "dza": "dz",
    "ceuta & melilla": "ea", 
    "ceuta and melilla": "ea", 
    "ceuta": "ea", 
    "melilla": "ea",
    "ecuador": "ec", 
    "the republic of ecuador": "ec", 
    "ecu": "ec",
    "estonia": "ee", 
    "the republic of estonia": "ee", 
    "est": "ee",
    "egypt": "eg", 
    "the arab republic of egypt": "eg", 
    "egy": "eg",
    "western sahara": "eh", 
    "the sahrawi arab democratic republic": "eh", 
    "esh": "eh",
    "eritrea": "er", 
    "the state of eritrea": "er", 
    "eri": "er",
    "spain": "es", 
    "the kingdom of spain": "es", 
    "esp": "es",
    "ethiopia": "et", 
    "the federal democratic republic of ethiopia": "et", 
    "eth": "et",
    "europe": "eu", 
    "european union": "eu",
    "finland": "fi", 
    "the republic of finland": "fi", 
    "fin": "fi",
    "fiji": "fj", 
    "the republic of fiji": "fj", 
    "fji": "fj",
    "falkland islands": "fk", 
    "the falkland islands": "fk", 
    "flk": "fk",
    "the federated states of micronesia": "fm", 
    "fsm": "fm", 
    "micronesia": "fm",
    "faroe islands": "fo", 
    "the faroe islands": "fo", 
    "fro": "fo",    
    "france": "fr", 
    "the french republic": "fr", 
    "fra": "fr",
    "gabon": "ga", 
    "the gabonese republic": "ga", 
    "gab": "ga",
    "northern ireland": "gb", 
    "great britain": "gb", 
    "uk": "gb", 
    "united kingdom": "gb", 
    "united kingdom of great britain and northern ireland": "gb", 
    "the united kingdom of great britain and northern ireland": "gb", 
    "gbr": "gb",
    "grenada": "gd", 
    "grd": "gd",
    "georgia": "ge", 
    "geo": "ge",
    "french guiana": "gf", 
    "guyane": "gf", 
    "guf": "gf",
    "guernsey": "gg", 
    "the bailiwick of guernsey": "gg", 
    "ggy": "gg",
    "ghana": "gh", 
    "the republic of ghana": "gh",
    "gha": "gh",
    "gibraltar": "gi", 
    "gib": "gi",
    "greenland": "gl", 
    "kalaallit nunaat": "gl", 
    "grl": "gl",
    "gambia": "gm", 
    "the republic of the gambia": "gm", 
    "gmb": "gm", 
    "the gambia": "gm",
    "guinea": "gn", 
    "the republic of guinea": "gn", 
    "gin": "gn",
    "guadeloupe": "gp", 
    "glp": "gp",
    "equatorial guinea": "gq", 
    "the republic of equatorial guinea": "gq", 
    "gnq": "gq",
    "greece": "gr", 
    "the hellenic republic": "gr", 
    "grc": "gr",
    "south georgia": "gs", 
    "south sandwich islands": "gs", 
    "south georgia and the south sandwich islands": "gs",
    "sgs": "gs",
    "guatemala": "gt", 
    "the republic of guatemala": "gt", 
    "gtm": "gt",
    "guam": "gu", 
    "the territory of guam": "gu", 
    "gum": "gu",
    "guinea-bissau": "gw", 
    "the republic of guinea-bissau": "gw", 
    "gnb": "gw",
    "guyana": "gy", 
    "the co-operative republic of guyana": "gy", 
    "guy": "gy",
    "hong kong": "hk",
    "the hong kong special administrative region of china": "hk", 
    "hkg": "hk",
    "heard island and mcdonald islands": "hm",
    "the territory of heard island and mcdonald islands": "hm", 
    "hmd": "hm",
    "honduras": "hn", 
    "the republic of honduras": "hn", 
    "hnd": "hn",
    "croatia": "hr", 
    "the republic of croatia": "hr", 
    "hrv": "hr",
    "haiti": "ht", 
    "the republic of haiti": "ht", 
    "hti": "ht",
    "hungary": "hu", 
    "hun": "hu",
    "canary islands": "ic",
    "indonesia": "id", 
    "the republic of indonesia": "id", 
    "idn": "id",
    "ireland": "ie", 
    "irl": 'ie',
    "israel": "il", 
    "the state of israel": "il", 
    "isr": "il",
    "isle of man": "im", 
    "the isle of man": "im", 
    "imn": "im",
    "india": "in", 
    "the republic of india": "in", 
    "ind": "in",
    "british indian ocean territory": "io", 
    "the british indian ocean territory": "io", 
    "iot": "io",
    "iraq": "iq", 
    "the republic of iraq": "iq", 
    "irq": "iq",
    "islamic republic of iran": "ir", 
    "iran": "ir", 
    "the islamic republic of iran": "ir", 
    "irn": "ir",
    "iceland": "is", 
    "the republic of iceland": "is", 
    "isl": "is",
    "italy": "it", 
    "the republic of italy": "it", 
    "ita": "it", 
    "the italian republic": "it",
    "jersey": "js", 
    "the bailiwick of jersey": "js", 
    "jey": "js",
    "jamaica": "jm", 
    "jam": "jm",
    "jordan": "jo", 
    "the hashemite kingdom of jordan": "jo", 
    "jor": "jo",
    "japan": "jp", 
    "jpn": "jp",
    "kenya": "ke", 
    "the republic of kenya": "ke", 
    "ken": "ke",
    "kyrgyzstan": "kg", 
    "the kyrgyz republic": "kg", 
    "kgz": "kg",
    "cambodia": "kh", 
    "the kingdom of cambodia": "kh", 
    "khm": "kh",
    "kiribati": "ki", 
    "the republic of kiribati": "ki", 
    "kir": "ki",
    "comoros": "km", 
    "the union of the comoros": "km", 
    "com": "km", 
    "the comoros": "km",
    "saint kitts and nevis": "kn",
    "kna": "kn",
    "democratic people's republic of korea": "kp", 
    "the democratic people's republic of korea": "kp", 
    "prk": "kp", 
    "north korea": "kp",
    "republic of korea": "kr", 
    "the republic of korea": "kr", 
    "kor": "kr", 
    "south korea": "kr",
    "kuwait": "kw", 
    "the state of kuwait": "kw", 
    "kwt": "kw",
    "cayman islands": "ky", 
    "the cayman islands": "ky", 
    "cym": "ky",
    "kazakhstan": "kz", 
    "the republic of kazakhstan": "kz", 
    "kaz": "kz",
    "laos": "la", 
    "lao people's democratic republic": "la", 
    "the lao people's democratic republic": "la", 
    "lao": "la",
    "lebanon": "lb", 
    "the lebanese republic": "lb", 
    "lbn": "lb",
    "saint lucia": "lc",
    "lca": "lc",
    "liechtenstein": "li", 
    "the principality of liechtenstein": "li", 
    "lie": "li",
    "sri lanka": "lk", 
    "the democratic socialist republic of sri lanka": "lk", 
    "lka": "lk",
    "liberia": "lr", 
    "the republic of liberia": "lr", 
    "lbr": "lr",
    "lesotho": "ls", 
    "the kingdom of lesotho": "ls", 
    "lso": "ls",
    "lithuania": "lt", 
    "the republic of lithuania": "lt", 
    "ltu": "lt",
    "luxembourg": "lu", 
    "the grand duchy of luxembourg": "lu", 
    "lux": "lu",
    "latvia": "lv", 
    "the republic of latvia": "lv", 
    "lva": "lv",
    "libya": "ly", 
    "the state of libya": "ly", 
    "lby": "ly",
    "morocco": "ma", 
    "the kingdom of morocco": "ma", 
    "mar": "ma",
    "monaco": "mc", 
    "the principality of monaco": "mc", 
    "mco": "mc",
    "republic of moldova": "md", 
    "the republic of moldova": "md", 
    "mda": "md", 
    "moldova": "md",
    "montenegro": "me", 
    "mne": "me",
    "saint martin": "mf", 
    "the collectivity of saint-martin": "mf", 
    "maf": "mf",
    "madagascar": "mg", 
    "the republic of madagascar": "mg", 
    "mdg": "mg",
    "marshall islands": "mh", 
    "the republic of the marshall islands": "mh", 
    "mhl": "mh", 
    "the marshall islands": "mh", 
    "north macedonia": "mk", 
    "the republic of north macedonia": "mk", 
    "mkd": "mk",
    "mali": "ml", 
    "the republic of mali": "ml", 
    "mli": "ml",
    "myanmar": "mm", 
    "the republic of the union of myanmar": "mm", 
    "mmr": "mm",
    "mongolia": "mn", 
    "mng": "mn",
    "macao": "mo", 
    "macao special administrative region of china": "mo", 
    "mac": "mo",
    "northern mariana islands": "mp", 
    "the northern mariana islands": "mp", 
    "the commonwealth of the northern mariana islands": "mp", 
    "mnp": "mp",
    "martinique": "mq", 
    "mtq": "mq",
    "mauritania": "mr", 
    "the islamic republic of mauritania": "mr", 
    "mrt": "mr",
    "montserrat": "mr", 
    "msr": "mr",
    "malta": "mt", 
    "the republic of malta": "mt", 
    "mlt": "mt",
    "mauritius": "mu", 
    "the republic of mauritius": "mu", 
    "mus": "mu",
    "maldives": "mv",
    "the republic of maldives": "mv", 
    "mdv": "mv",
    "malawi": "mw", 
    "the republic of malawi": "mw", 
    "mwi": "mw",
    "mexico": "mx", 
    "the united mexican states": "mx", 
    "mex": "mx",
    "malaysia": "my", 
    "mys": "my",
    "mozambique": "mz", 
    "the republic of mozambique": "mz", 
    "moz": "mz",
    "namibia": "na", 
    "the republic of namibia": "na", 
    "nam": "na",
    "new caledonia": "nc", 
    "ncl": "nc",
    "niger": "ni", 
    "the republic of the niger": "ni", 
    "ner": "ni", 
    "the niger": "ni",
    "norfolk island": "nf", 
    "the territory of norfolk island": "nf", 
    "nfk": "nf",
    "nigeria": "ng", 
    "the federal republic of nigeria": "ng", 
    "nga": "ng",
    "nicaragua": "ni", 
    "the republic of nicaragua": "ni", 
    "nic": "ni",
    "netherlands": "nl", 
    "the kingdom of the netherlands": "nl", 
    "nld": "nl", 
    "the netherlands": "nl",
    "holland": "nl",
    "norway": "no", 
    "the kingdom of norway": "no", 
    "nor": "no",
    "nepal": "np", 
    "the federal democratic republic of nepal": "np", 
    "npl": "np",
    "nauru": "nr",
    "the republic of nauru": "nr", 
    "nru": "nr",
    "niue": "nu", 
    "niu": "nu",
    "new zealand": "nz", 
    "nzl": "nz",
    "oman": "om", 
    "the sultanate of oman": "om",
    "omn": "om",
    "panama": "pa", 
    "the republic of panama": "pa", 
    "pan": "pa", 
    "the republic of panamá": "pa", 
    "panamá": "pa",
    "peru": "pr", 
    "the republic of peru": "pr", 
    "per": "pr", 
    "the republic of perú": "pr", 
    "perú": "pr",
    "french polynesia": "pf", 
    "pyf": "pf",
    "papua new guinea": "pg", 
    "independent state of papua new guinea": "pg", 
    "png": "pg", 
    "the independent state of papua new guinea": "pg",
    "philippines": "ph", 
    "the republic of the philippines": "ph", 
    "phl": "ph", 
    "the philippines": "ph",
    "pakistan": "pk", 
    "the islamic republic of pakistan": "pk", 
    "pak": "pk",
    "poland": "pl", 
    "the republic of poland": "pl", 
    "pol": "pl",
    "saint pierre": "pm", 
    "miquelon": "pm", 
    "saint pierre and miquelon": "pm", 
    "the overseas collectivity of saint-pierre and miquelon": "pm", 
    "spm": "pm",
    "oeno": "pn", 
    "ducie": "pn", 
    "henderson": "pn", 
    "pitcairn": "pn", 
    "the pitcairn, henderson, ducie and oeno islands": "pn", 
    "pcn": "pn",
    "puerto rico": "pr", 
    "the commonwealth of puerto rico": "pr", 
    "pri": "pr",
    "state of palestine": "ps", 
    "palestine": "ps", 
    "the state of palestine": "ps", 
    "pse": "ps",
    "portugal": "pt", 
    "the portuguese republic": "pt", 
    "prt": "pt",
    "palau": "pw", 
    "the republic of palau": "pw", 
    "plw": "pw",
    "paraguay": "py", 
    "the republic of paraguay": "py", 
    "pry": "py",
    "qatar": "qa", 
    "the state of qatar": "qa", 
    "qat": "qa",
    "reunion": "re", 
    "réunion": "re",
    "reu": "re",
    "romania": "ro", 
    "rou": "ro",
    "serbia": "rs", 
    "the republic of serbia": "rs", 
    "srb": "rs",
    "russia": "ru", 
    "russian federation": "ru", 
    "the russian federation": "ru", 
    "rus": "ru",
    "rwanda": "rw", 
    "the republic of rwanda": "rw", 
    "rwa": "rw",
    "saudi arabia": "sa", 
    "the kingdom of saudi arabia": "sa", 
    "sau": "sa", 
    "ksa": "sa",
    "solomon islands": "sb", 
    "slb": "sb", 
    "the solomon islands": "sb",
    "seychelles": "sc", 
    "the republic of seychelles": "sc", 
    "syc": "sc",
    "sudan": "sd", 
    "the republic of the sudan": "sd", 
    "sdn": "sd", 
    "the sudan": "sd",
    "sweden": "se", 
    "the kingdom of sweden": "se", 
    "swe": "se",
    "singapore": "sg", 
    "the republic of singapore": "sg", 
    "sgp": "sg",
    "ascension": "sh", 
    "saint helena": "sh", 
    "saint helena ascension island tristan da cunha": "sh", 
    "saint helena, ascension and tristan da cunha": "sh", 
    "shn": "sh",
    "slovenia": "si", 
    "the republic of slovenia": "si", 
    "svn": "si",
    "svalbard jan mayen": "sj", 
    "svalbard and jan mayen": "sj", 
    "sjm": "sj",
    "slovakia": "sk", 
    "the slovak republic": "sk", 
    "svk": "sk",
    "sierra leone": "sl", 
    "the republic of sierra leone": "sl", 
    "sle": "sl",
    "san marino": "sm", 
    "the republic of san marino": "sm", 
    "smr": "sm",
    "senegal": "sn", 
    "the republic of senegal": "sn",
    "sen": "sn",
    "somalia": "so", 
    "the federal republic of somalia": "so", 
    "som": "so",
    "suriname": "sr", 
    "the republic of suriname": "sr", 
    "sur": "sr",
    "south sudan": 'ss', 
    "the republic of south sudan": "ss", 
    "ssd": "ss",
    "são tomé and príncipe": "st", 
    "príncipe": "st",
    "são tomé": "st", 
    "principe": "st", 
    "sao tome": "st", 
    "sao tome and principe": "st", 
    "the democratic republic of sao tome and principe": "st", 
    "stp": "st", 
    "the democratic republic of são tomé and príncipe": "st",
    "el salvador": "sv", 
    "the republic of el salvador": "sv", 
    "slv": "sv",
    "sint maarten": "sx", 
    "sxm": "sx",
    "syria": "sy", 
    "syrian arab republic": "sy", 
    "the syrian arab republic": "sy", 
    "syr": "sy",
    "eswatini": "sz", 
    "the kingdom of eswatini": "sz", 
    "swz": "sz",
    "tristan da cunha": "ta",
    "turks and caicos islands": "tc", 
    "the turks and caicos islands": "tc", 
    "tca": "tc",
    "chad": "td", 
    "the republic of chad": "td", 
    "tcd": "td",
    "french southern territories": "tf", 
    "the french southern territories": "tf", 
    "the french southern and antarctic lands": "tf", 
    "atf": "tf",
    "togo": "tg", 
    "the togolese republic": "tg", 
    "tgo": "tg",
    "thailand": "th", 
    "the kingdom of thailand": "th", 
    "tha": "th",
    "tajikistan": "tj", 
    "the republic of tajikistan": "tj", 
    "tjk": "tj",
    "tokelau": "tk", 
    "tkl": "tk",
    "the democratic republic of timor leste": "tl", 
    "timor leste": "tl", 
    "timor-leste": "tl", 
    "the democratic republic of timor-leste": "tl", 
    "tls": "tl",
    "turkmenistan": "tm", 
    "tkm": "tm",
    "tunisia": "tn", 
    "the republic of tunisia": "tn", 
    "tun": "tn",
    "tonga": "to", 
    "the kingdom of tonga": "to", 
    "ton": 'to',
    "turkey": "tr", 
    "the republic of turkey": "tr", 
    "tur": "tr",
    "tobago": "tt", 
    "trinidad": "tt", 
    "trinidad and tobago": "tt",
    "the republic of trinidad and tobago": "tt"
    "tto": "tt",
    "tuvalu": "tv", 
    "tuv": "tv",
    "taiwan": "tw", 
    "the republic of china": "tw", 
    "twn": "tw",
    "united republic of tanzania": "tz", 
    "the united republic of tanzania": "tz", 
    "tza": "tz", 
    "tanzania": "tz",
    "ukraine": "ua", 
    "ukr": "ua",
    "uganda": "ug",
    "the republic of uganda": "ug", 
    "uga": "ug",
    "baker island": "um", 
    "howland island": "um", 
    "jarvis island": "um", 
    "johnston atoll": "um", 
    "kingman reef": "um", 
    "midway atoll": "um", 
    "navassa island": "um", 
    "palmyra atoll": "um", 
    "wake island": "um", 
    "united states minor outlying islands": "um", 
    "the united states minor outlying islands": "um", 
    "baker island, howland island, jarvis island, johnston atoll, kingman reef, midway atoll, navassa island, palmyra atoll, and wake island": "um", 
    "umi": "um",
    "united nations": "un",
    "united states": "us", 
    "united states of america": "us", 
    "the united states of america": "us",
    "usa": "us",
    "uruguay": "uy", 
    "the eastern republic of uruguay": "uy", 
    "ury": "uy", 
    "the oriental republic of uruguay": "uy",
    "uzbekistan": "uz", 
    "the republic of uzbekistan": "uz", 
    "uzb": "uz",
    "vatican": "va",
    "holy see": "va", 
    "the holy see": "va", 
    "vat": "va",
    "saint vincent and the grenadines": "vc", 
    "vct": "vc",
    "bolivarian republic of venezuela": "ve", 
    "the bolivarian republic of venezuela": "ve", 
    "ven": "ve", 
    "venezuela": "ve",
    "virgin islands": "vg", 
    "the virgin islands": "vg", 
    "vgb": "vg",
    "virgin islands": "vi", 
    "the virgin islands of the united states": "vi", 
    "vir": "vi",
    "vietnam": "vn", 
    "viet nam": "vn", 
    "the socialist republic of vietnam": "vn", 
    "the socialist republic of viet nam": "vn",
    "vnm": "vn",
    "vanuatu": "vu", 
    "the republic of vanuatu": "vu", 
    "vut": "vu",
    "futuna islands": "wf", 
    "futuna": "wf",
    "wallis": "wf", 
    "wallis and futuna": "wf", 
    "the territory of the wallis and futuna islands": "wf", 
    "wlf": "wf",
    "samoa": "ws", 
    "the independent state of samoa": "ws", 
    "wsm": "ws",
    "kosovo": "xk", 
    "rks": "xk",
    "yemen": "ye", 
    "the republic of yemen": "ye", 
    "yem": "ye",
    "mayotte": "yt", 
    "the department of mayotte": "yt", 
    "myt": "yt",
    "south africa": "za", 
    "the republic of south africa": "za", 
    "zaf": "za",
    "zambia": "zm", 
    "the republic of zambia": "zm", 
    "zmb": "zm",
    "zimbabwe": "zw", 
    "the republic of zimbabwe": "zw", 
    "zwe": "zw"
    "england": "en", 
    "eng": "en",
    "wales": "wa"
}